import asyncio
import re

from rich.console import Console
from core.llm import chat

from core.agent_state import AgentState
from core.action_engine import agent_step
from core.paths import get_desktop_path
from core.pending_action import format_confirmation_message
from agents.research_agent import ResearchAgent
from tools.leetcode_tool import (
    fetch_solution_from_web,
    _extract_python_code,
    format_problem_for_llm,
    parse_pasted_leetcode,
)
from tools.tool_registry import ToolRegistry

console = Console()


class LeetCodeSkill:
    """
    Dedicated LeetCode workflow — does not rely on Qwen to figure out steps.

    Paste or research → Plan → Code (model) → Pending confirmation → Save to Desktop
    """

    def __init__(self):
        self.state = AgentState()
        self.registry = ToolRegistry()
        self.registry.setup()

    async def run(self, user_input: str) -> str:
        console.print("\n[bold cyan]=== LeetCode Workflow ===[/bold cyan]")

        self.state.current_task = {
            "goal": user_input,
            "workflow": "leetcode",
            "step": "Researching",
        }
        self.state.save()

        problem = self._resolve_problem(user_input)
        if not problem:
            # Follow-up like "write it in python on desktop" — reuse last pasted problem
            problem = (self.state.current_task or {}).get("leetcode_problem")
        if not problem:
            # Search recent conversation for a pasted statement
            for msg in reversed(self.state.conversation_history or []):
                if msg.get("role") != "user":
                    continue
                problem = parse_pasted_leetcode(msg.get("content") or "")
                if problem:
                    break

        ctx_text = ""
        if not problem:
            researcher = ResearchAgent()
            ctx = await researcher.execute(user_input)
            problem = (self.state.current_task or {}).get("leetcode_problem")
            ctx_text = ctx.to_prompt() if ctx else ""
            if not problem:
                diag = (ctx.extracted_text or ctx.summary) if ctx else ""
                return (
                    "LeetCode research failed. Paste the full problem statement "
                    f"(title, examples, constraints) and say **solve this**.\n{diag}"
                )
        else:
            ctx_text = format_problem_for_llm(problem)
            # Persist so follow-ups ("write python on desktop") keep context
            self.state.current_task["leetcode_problem"] = problem
            self.state.current_task["leetcode_sections"] = {
                "title": problem.get("title"),
                "statement": problem.get("description"),
            }
            self.state.save()

        console.print(f"\n[bold]Problem:[/bold] #{problem['id']} — {problem['title']}")

        self.state.current_task["step"] = "Planning"
        self.state.current_task["leetcode_problem"] = problem
        self.state.save()
        console.print("\n[bold cyan]--- Planner ---[/bold cyan]")
        plan = await agent_step(
            "Planner",
            f"Create a concise algorithm plan for this LeetCode problem:\n{ctx_text}",
        )
        console.print(plan)

        self.state.current_task["step"] = "Coding"
        self.state.save()
        console.print("\n[bold cyan]--- Coder (local model) ---[/bold cyan]")

        code = await self._generate_solution(problem, plan, ctx_text)
        console.print(f"[dim]Generated {len(code)} chars of code[/dim]")

        desktop = get_desktop_path()
        safe_title = re.sub(r"[^a-zA-Z0-9_-]", "_", problem["title"].lower())
        filename = f"leetcode_{problem['id']}_{safe_title}.py"
        file_path = str(desktop / filename)

        header = (
            f"# LeetCode #{problem['id']} - {problem['title']}\n"
            f"# Difficulty: {problem['difficulty']}\n"
            f"# URL: {problem['url']}\n"
            f"# Topics: {', '.join(problem.get('tags', []))}\n"
            f"# Generated by Immortility\n\n"
        )
        final_content = header + code

        self.state.current_task["step"] = "AwaitingConfirmation"
        self.state.pending_action = {
            "tool": "create_file",
            "args": {"path": file_path, "content": final_content},
            "workflow": "leetcode",
        }
        self.state.save()

        msg = format_confirmation_message("create_file", {"path": file_path})
        console.print(f"\n[bold yellow]{msg}[/bold yellow]")
        console.print("[dim]Solution preview:[/dim]")
        console.print(f"[green]{final_content[:800]}[/green]")
        preview = final_content[:500]
        return (
            f"{msg}\n\n"
            f"**Preview (model solution):**\n```python\n{preview}\n```\n"
            f"Say **yes** to save on your Desktop."
        )

    def _resolve_problem(self, user_input: str) -> dict | None:
        pasted = parse_pasted_leetcode(user_input)
        if pasted:
            console.print("[green]Using pasted LeetCode problem (no web required).[/green]")
            return pasted
        # Stored from earlier turn
        task = self.state.current_task or {}
        if task.get("workflow") == "leetcode" and task.get("leetcode_problem"):
            return task["leetcode_problem"]
        return None

    async def _generate_solution(self, problem: dict, plan: str, research: str) -> str:
        # Prefer the local/configured model for pasted problems so Immortility "owns" the solve
        if not problem.get("from_paste"):
            try:
                web_code = await fetch_solution_from_web(problem)
                if web_code:
                    console.print("[green]Using verified web solution.[/green]")
                    return web_code
            except Exception as e:
                console.print(f"[yellow]Web solution fetch failed: {e}[/yellow]")

        console.print("[cyan]Generating solution with Immortility LLM…[/cyan]")
        prompt = (
            f"Write a complete Python LeetCode solution.\n\n"
            f"Problem:\n{research}\n\n"
            f"Plan:\n{plan}\n\n"
            f"Requirements:\n"
            f"- Use class Solution with an appropriate method signature.\n"
            f"- Handle constraints efficiently (n up to 1e5 when stated).\n"
            f"- Include a small `if __name__ == '__main__'` self-check with the examples.\n"
            f"- Output ONLY Python code, no markdown fences."
        )

        response = await asyncio.to_thread(
            chat,
            model="auto",
            messages=[
                {
                    "role": "system",
                    "content": (
                        "You are Immortility solving LeetCode in Python. "
                        "Output only raw Python code. No explanations."
                    ),
                },
                {"role": "user", "content": prompt},
            ],
            think=False,
        )
        raw = response["message"]["content"].strip()
        extracted = _extract_python_code(raw)
        return extracted or raw
